spring:
  application.name: fridge-server
  ai.mcp.server:
    name: ${spring.application.name}
    protocol: STREAMABLE
server.port: 8081
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.probes.enabled: true
logging.level.io.modelcontextprotocol.server: DEBUG

app.available-ingredients-in-fridge: bacon,onions
